//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manament_Store_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangNCC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHangNCC()
        {
            this.ChiTietDonHangNCCs = new HashSet<ChiTietDonHangNCC>();
            this.PhieuNhapHangs = new HashSet<PhieuNhapHang>();
        }
    
        public int MaDatHang { get; set; }
        public string MaNhaCungCap { get; set; }
        public int MaCuaHang { get; set; }
        public int MaNhanVien { get; set; }
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        public System.DateTime NgayGHDuKien { get; set; }
        public decimal TongTien { get; set; }
        public string GhiChu { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayNHTT { get; set; }
        public string POFilePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHangNCC> ChiTietDonHangNCCs { get; set; }
        public virtual CuaHang CuaHang { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhapHang> PhieuNhapHangs { get; set; }
    }
}
