//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manament_Store_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DonHangNCC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHangNCC()
        {
            this.ChiTietDonHangNCCs = new HashSet<ChiTietDonHangNCC>();
        }

        [Display(Name ="Mã Đặt Hàng")]
        public int MaDatHang { get; set; }
        [Display(Name ="Nhà Cung Cấp")]
        public string MaNhaCungCap { get; set; }
        [Display(Name = "Cửa Hàng")]
        public int MaCuaHang { get; set; }
        [Display(Name = "Họ và Tên Nhân Viên")]
        public int MaNhanVien { get; set; }
        [Display(Name = "Ngày Đặt Hàng")]
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        [Display(Name = "Ngày Giao Hàng Dự Kiến")]
        public System.DateTime NgayGHDuKien { get; set; }
        [Display(Name = "Tổng Tiền")]
        public decimal TongTien { get; set; }
        [Display(Name = "Ghi Chú")]
        public string GhiChu { get; set; }
        [Display(Name = "Trạng Thái")]
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHangNCC> ChiTietDonHangNCCs { get; set; }
        public virtual CuaHang CuaHang { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
