//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manament_Store_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuNhapHang()
        {
            this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
        }
    
        public string MaPhieuNhap { get; set; }
        public string MaNhaCungCap { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public int MaNhanVien { get; set; }
        public string GhiChu { get; set; }
        public string TrangThai { get; set; }
        public int MaCuaHang { get; set; }
        public int MaKho { get; set; }
        public int MaDonDatHang { get; set; }
        public string MaDanhMuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual CuaHang CuaHang { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual DanhMucSanPham DanhMucSanPham { get; set; }
        public virtual DonHangNCC DonHangNCC { get; set; }
    }
}
