//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manament_Store_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCauNghiPhep
    {
        public int YeuCauID { get; set; }
        public int MaNhanVien { get; set; }
        public int SoNgayNghi { get; set; }
        public System.DateTime NgayBatDauNghi { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string LyDo { get; set; }
        public string TrangThai { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
